
include Makefile

MAIN=./MarDyn.cpp
SOURCES := $(filter-out $(MAIN),$(SOURCES))
CXXFLAGS+= -fPIC 


lib: .deps $(OBJECTS)
	$(CXX) $(LDFLAGS) -shared -Wl,-soname,libMardyn.so.1 -o libMardyn.so.1.0 $(OBJECTS)

#lib: .deps $(OBJECTS)
#	ar rcs Mardyn.a $(OBJECTS)

