
include Makefile

MAIN=./MarDyn.cpp
SOURCES := $(filter-out $(MAIN),$(SOURCES))
CXXFLAGS+= -fPIC 

#lib: .deps $(OBJECTS)
#	$(CXX) $(LDFLAGS) -shared -Wl,-soname,Mardyn.so -lc -o libMardyn.so $(OBJECTS)

lib: .deps $(OBJECTS)
	ar rcs Mardyn.a $(OBJECTS)

