#!/bin/bash
fname=$1
# check if the file is OK
if ! check-OK $fname ; then
	echo "- MFLOP/sec"
	exit 1
fi
FLOPsecWithUnits=`cat $fname | grep "FLOP/sec" | tail -n 1 | cut -d ":" -f 2 | cut -d "(" -f 1`
echo $FLOPsecWithUnits
