/*
 * MardynConfigLegacyWriter.cpp
 *
 * @Date: 13.09.2011
 * @Author: eckhardw
 */

#include "MardynConfigLegacyWriter.h"
#include "MardynConfiguration.h"
#include <fstream>

using namespace std;

MardynConfigLegacyWriter::MardynConfigLegacyWriter() {
}

MardynConfigLegacyWriter::~MardynConfigLegacyWriter() {
}

void MardynConfigLegacyWriter::writeConfigFile(const std::string& directory, const std::string& fileName,
		const MardynConfiguration& config) {

	string fullName = directory + "/" + fileName;
	ofstream output(fullName.c_str());
	output << "MDProjectConfig\n" << endl;

	output << "# THIS CONFIGURATION WAS GENERATED BY THE SCENARIO-GENERATOR!\n" << endl;

	output << "timestepLength " << config.getTimestepLength() << endl;
	output << "cutoffRadius " << config.getCutoffRadius() << endl;
	output << "phaseSpaceFile OldStyle " << config.getScenarioName() << ".inp" << endl;
	output << "datastructure LinkedCells 1" << endl;

	output.close();
}
