# armadillo library
option(ENABLE_ARMADILLO "Add armadillo" ON)
if(ENABLE_ARMADILLO)
  message(STATUS "Armadillo enabled")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DMARDYN_ARMADILLO")
  find_library(BLAS_LIB blas)
  find_library(LAPACK_LIB lapack)
  if(BLAS_LIB AND LAPACK_LIB)
      message(STATUS "libblas and liblapack found")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DARMA_DONT_USE_WRAPPER")
  else()
      message(WARNING "blas or lapack not found")
      unset(BLAS_LIB CACHE)
      unset(LAPACK_LIB CACHE)
  endif()
else()
  message(STATUS "Armadillo disabled")
  unset(BLAS_LIB CACHE)
  unset(LAPACK_LIB CACHE)
endif()
