# armadillo library
option(ENABLE_ARMADILLO "Add armadillo" OFF)
if(ENABLE_ARMADILLO)
  message(STATUS "Armadillo enabled")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DMARDYN_ARMADILLO")
  find_package(BLAS)
  find_package(LAPACK)
  if(BLAS_FOUND AND LAPACK_FOUND)
      message(STATUS "libblas and liblapack found:")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DARMA_DONT_USE_WRAPPER")
      set(BLAS_LIB ${BLAS_LIBRARIES} )
      set(LAPACK_LIB ${LAPACK_LIBRARIES} )
      message(STATUS "  BLAS_LIB: ${BLAS_LIB}")
      message(STATUS "  LAPACK_LIB: ${LAPACK_LIB}")
  else()
      message(WARNING "blas or lapack not found, but both are required for amadillo!")
      message(WARNING "  BLAS_FOUND: ${BLAS_FOUND}")
      message(WARNING "  LAPACK_FOUND: ${LAPACK_FOUND}")
      unset(BLAS_LIB CACHE)
      unset(LAPACK_LIB CACHE)
  endif()
else()
  message(STATUS "Armadillo disabled")
  unset(BLAS_LIB CACHE)
  unset(LAPACK_LIB CACHE)
endif()
