option(ENABLE_CCACHE "Use ccache for accellerated compilation through caching" OFF)
if (ENABLE_CCACHE)
    find_program(CCACHE_FOUND ccache)
    if (CCACHE_FOUND)
        message(STATUS "ccache found, building with ccache")
        SET(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_FOUND} CACHE STRING "ccache executable")
    else()
        message(WARNING "ccache not found, building without ccache")
    endif (CCACHE_FOUND)
else ()
    message(STATUS "ccache disabled")
endif ()