option(MAMICO_COUPLING "Couple with MaMiCo" OFF)
if (MAMICO_COUPLING)
	message(STATUS "MaMiCo coupling enabled. ls1 mardyn will compile as library. No executable will be created.")
	set(MAMICO_COMPILE_DEFINITIONS MAMICO_COUPLING MDDim3)
	option(MAMICO_ENABLE_FPIC "Enable -fPIC flag for MaMiCo python bindings" OFF)
	set(MAMICO_SRC_DIR CACHE PATH "Root directory of the MaMiCo codebase")
    if(NOT MAMICO_SRC_DIR)
		message(FATAL_ERROR "MaMiCo source directory not specified.")
	endif()
	if(ENABLE_MPI)
		set(MAMICO_MPI_DEFINITIONS MDCoupledParallel TarchParallel)
	endif()
	if(MAMICO_ENABLE_FPIC)
		set(MAMICO_COMPILE_OPTIONS "${MAMICO_COMPILE_OPTIONS} -fPIC")
	endif()
else()
    message(STATUS "MaMiCo coupling disabled.")
endif()