option(MAMICO_COUPLING "Couple with MaMiCo" OFF)
if (MAMICO_COUPLING)
	message(STATUS "MaMiCo coupling enabled. mardyn will compile as library. No executable will be created.")
	set(MAMICO_COMPILE_DEFINITIONS MAMICO_COUPLING MDDim3)
	set(MAMICO_SRC_DIR CACHE PATH "Root directory of the MaMiCo codebase")
    if(NOT MAMICO_SRC_DIR)
		message(FATAL_ERROR "MaMiCo source directory not specified.")
	endif()
	if(ENABLE_MPI)
		set(MAMICO_MPI_DEFINITIONS MDCoupledParallel TarchParallel)
	endif()
else()
    message(STATUS "MaMiCo coupling disabled.")
endif()