# mpi
option(ENABLE_MPI "Enable MPI" OFF)
if(ENABLE_MPI)
    message(STATUS "MPI Enabled")
    find_package(MPI)
    include_directories(${MPI_CXX_INCLUDE_DIRS})
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_MPI")
else()
    message(STATUS "MPI Disabled")
endif()